### ISSUE TITLE
cargo-collect

### ISSUE THREAD

**Issue by rluvaton** [TalRoni/crates-registry#20]
FYI, I've forked the `cargo-collect` and improve it, if you wanna take a look:

- https://github.com/rluvaton/cargo-collect

**Comment by rluvaton** [comment]
Also, would you consider moving from GitLab to GithHub, it's much nicer?

**Comment by TalRoni** [comment]
Looks great! I moved the repository to GitHub and let's unite the repositories again. 
I also moved Cargo Upload to Github with your MRs.
I appreciate your contribution to the repositories.
